CREATE DATABASE IF NOT EXISTS mood_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mood_db;

CREATE TABLE IF NOT EXISTS mood_reports (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id VARCHAR(64) NOT NULL,
  date DATE NOT NULL,
  mood_score TINYINT UNSIGNED NOT NULL CHECK (mood_score BETWEEN 1 AND 5),
  mood_label VARCHAR(50) NULL,
  notes VARCHAR(1000) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_user_date (user_id, date),
  KEY idx_user_date (user_id, date),
  KEY idx_date (date)
) ENGINE=InnoDB;
